### ISSUE TITLE
Cases with zero input should return exceptions

### ISSUE THREAD

**Issue by senddownrain** [Ivan-Shymanovich/tryruby#1]
a = Rational_Number.new(5, 0)
b = Rational_Number.new(3,0)

process please all situations with invalid inputs.

**Comment by senddownrain** [comment]
После того как посчитаешь что баг пофиксан, отпишись по нему или переведи в новый статус.

**Comment by Ivan-Shymanovich** [comment]
Ошибки по форматированию, которые обнаружил, исправил. Переименовал папки и файл.
