### ISSUE TITLE
Incorrect comparison 

### ISSUE THREAD

**Issue by senddownrain** [Ivan-Shymanovich/tryruby#2]
a = RationalNumber.new(4,4)
b = RationalNumber.new(1,1)
a == b
a.eql? b
Что выведет?

a > b 
не работает

Извини, не очень внимательно посмотрел на вторую часть лабы
Реализовать в классе рациональных чисел интерфейсы для проверки двух чисел на равенство и порядкового сравнения.

Тут идет речь о интерфейсах. В руби это миксины(примеси). Как правило в языках есть системный интерфейс(миксин), реализуя который класс полноценно будет учавстовать в операциях сравнения.

Обрати пожалуйста внимания на 
ruby comparable mixin

Класс также должен правильно работать в операциях сортировки в массиве.
и выполнять правильно метод s4.between?(s1, s3)

**Comment by Ivan-Shymanovich** [comment]
Добавил к коду примесь Comparable. Работают корректно все методы сравнения, в том числе и a.eql? b, s4.between?(s1, s3)

**Comment by senddownrain** [comment]
походу не вкоммитал

**Comment by Ivan-Shymanovich** [comment]
Вкоммитил
