### ISSUE TITLE
Real numbers in constructor

### ISSUE THREAD

**Issue by senddownrain** [Ivan-Shymanovich/tryruby#6]
b = RationalNumber.new(4,0.2) 
very intresting results

**Comment by Ivan-Shymanovich** [comment]
Тут я следовал условию задачи, где указано, что в знаменателе должно находится натуральное число.

**Comment by senddownrain** [comment]
задача класа - представить число 
Создать класс для представления рационального числа, т.е. числа вида n/m, где n – целое, m – натуральное число.

ну а реализация это другое.
ты мог получать в конструкторе массив, мог строку и т.д.
в условии задачи ничего не сказано о входных данных
поэтому в каком виде они не были бы - ты должен их валидировать.

**Comment by Ivan-Shymanovich** [comment]
Сделал проверку на входные данные, в проге увидишь все. От very interesting results избавился, но появилась проблема с выводом чисел другая (выводятся как Float c .0)
